# Generated by Django 4.2.1 on 2023-05-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_alter_banco_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='cliente',
            field=models.CharField(max_length=20),
        ),
    ]
